"""novos campos in User model

Revision ID: 384231edfdb4
Revises: e11538f2750c
Create Date: 2023-06-21 18:15:55.417002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '384231edfdb4'
down_revision = 'e11538f2750c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
